# Generated by Django 5.2.2 on 2025-06-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentPosting',
            fields=[
                ('postingID', models.AutoField(primary_key=True, serialize=False)),
                ('postingTitle', models.CharField(max_length=1000)),
                ('postingDate', models.DateField()),
                ('floorNumber', models.CharField(max_length=20)),
                ('buildingNumber', models.CharField(max_length=20)),
                ('streetName', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('ownershipType', models.CharField(max_length=100)),
                ('institutionalSeller', models.BooleanField()),
            ],
        ),
    ]
