# Generated by Django 5.2.2 on 2025-06-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziauki_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentposting',
            name='buildingNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentposting',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentposting',
            name='floorNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentposting',
            name='institutionalSeller',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='apartmentposting',
            name='ownershipType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentposting',
            name='postingDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='apartmentposting',
            name='streetName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
