# Generated by Django 5.2.2 on 2025-07-04 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dziauki_ecommerce', '0002_alter_apartmentposting_buildingnumber_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApartmentPosting',
            new_name='PropertyPosting',
        ),
    ]
