# Generated by Django 5.2.2 on 2025-07-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziauki_ecommerce', '0003_rename_apartmentposting_propertyposting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyposting',
            old_name='floorNumber',
            new_name='floor',
        ),
        migrations.AddField(
            model_name='propertyposting',
            name='forSaleFlag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertyposting',
            name='otherFeesAndBills',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propertyposting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='propertyposting',
            name='roomNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propertyposting',
            name='usableArea',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='propertyposting',
            name='institutionalSeller',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
