# Generated by Django 5.2.2 on 2025-08-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziauki_ecommerce', '0004_rename_floornumber_propertyposting_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyposting',
            name='buildingNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyposting',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='propertyposting',
            name='floor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyposting',
            name='institutionalSeller',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='propertyposting',
            name='otherFeesAndBills',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='propertyposting',
            name='ownershipType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='propertyposting',
            name='postingDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertyposting',
            name='roomNumber',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertyposting',
            name='streetName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
