# Generated by Django 5.2.2 on 2025-08-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziauki_ecommerce', '0005_alter_propertyposting_buildingnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyposting',
            name='postingDate',
        ),
        migrations.AlterField(
            model_name='propertyposting',
            name='otherFeesAndBills',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertyposting',
            name='roomNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
